<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Models\JobOrder;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * Two ways to see order status: show() lets anyone check by tracking code
 * alone, no account needed (consumed by /track/[code]) — mirrors a
 * courier/delivery tracking page, the tracking_code itself is the
 * credential. myOrders() is the authenticated counterpart — a logged-in
 * customer's own cross-store order list (consumed by /account/orders),
 * scoped by their real customer_id instead of needing every code memorized.
 */
class JobOrderTrackingController extends Controller
{
    /**
     * Cross-store "My Orders" for whoever is logged in — the authenticated
     * counterpart to show() above, same safe field subset (no staff
     * assignments/internal notes), just scoped by the real customer_id
     * instead of a guessable-free tracking code. No role gate: filters by
     * the caller's own id, so it's inherently scoped to their own data.
     */
    public function myOrders(Request $request): JsonResponse
    {
        $jobOrders = JobOrder::where('customer_id', $request->user()->id)
            ->with(['store:id,name,slug,logo_path', 'service:id,name', 'catalogItem:id,name'])
            ->latest()
            ->paginate($request->input('per_page', 20));

        $jobOrders->getCollection()->transform(fn (JobOrder $jobOrder) => [
            'id' => $jobOrder->id,
            'order_number' => $jobOrder->order_number,
            'tracking_code' => $jobOrder->tracking_code,
            'status' => $jobOrder->status,
            'garment_category' => $jobOrder->garment_category,
            'catalog_item_name' => $jobOrder->catalogItem?->name,
            'service_name' => $jobOrder->service?->name,
            'is_rush' => (bool) $jobOrder->is_rush,
            'due_date' => $jobOrder->due_date,
            'total_amount' => (float) $jobOrder->total_amount,
            'balance' => (float) $jobOrder->balance,
            'payment_status' => $jobOrder->payment_status,
            'created_at' => $jobOrder->created_at,
            'store' => $jobOrder->store ? [
                'name' => $jobOrder->store->name,
                'slug' => $jobOrder->store->slug,
                'logo_path' => $jobOrder->store->logo_path,
            ] : null,
        ]);

        return response()->json([
            'success' => true,
            'data' => $jobOrders->items(),
            'meta' => [
                'current_page' => $jobOrders->currentPage(),
                'last_page' => $jobOrders->lastPage(),
                'total' => $jobOrders->total(),
            ],
        ]);
    }

    /**
     * Single-order detail for the "My Orders" list — keyed by the order's
     * own id, not tracking_code. tracking_code is only ever generated by
     * JobOrderController::store; seeded/legacy rows can predate it and
     * would otherwise be permanently unopenable from an authenticated
     * customer's own order list even though they own the order and don't
     * need a guessable code to prove it. Ownership check replaces the
     * "the code is the credential" trust model show() above uses.
     */
    public function myOrderDetail(Request $request, JobOrder $jobOrder): JsonResponse
    {
        if ($jobOrder->customer_id !== $request->user()->id) {
            return response()->json(['success' => false, 'message' => 'Order not found.'], 404);
        }

        $jobOrder->load(['store:id,name,slug,logo_path', 'service:id,name', 'catalogItem:id,name', 'staffStages']);

        return response()->json([
            'success' => true,
            'data' => [
                'order_number' => $jobOrder->order_number,
                'tracking_code' => $jobOrder->tracking_code,
                'status' => $jobOrder->status,
                'garment_category' => $jobOrder->garment_category,
                'catalog_item_name' => $jobOrder->catalogItem?->name,
                'service_name' => $jobOrder->service?->name,
                'is_rush' => (bool) $jobOrder->is_rush,
                'due_date' => $jobOrder->due_date,
                'estimated_ready_at' => $jobOrder->estimated_ready_at,
                'total_amount' => (float) $jobOrder->total_amount,
                'balance' => (float) $jobOrder->balance,
                'payment_status' => $jobOrder->payment_status,
                'created_at' => $jobOrder->created_at,
                'updated_at' => $jobOrder->updated_at,
                'repair_note' => $jobOrder->custom_order_data['repair_note'] ?? null,
                'customer_material_status' => $jobOrder->customer_material_status,
                'progress_photos' => $jobOrder->progress_photos,
                'stage_timestamps' => $this->buildStageTimestamps($jobOrder),
                'appointments' => $this->buildCustomerSafeAppointments($jobOrder),
                'store' => $jobOrder->store ? [
                    'name' => $jobOrder->store->name,
                    'slug' => $jobOrder->store->slug,
                    'logo_path' => $jobOrder->store->logo_path,
                ] : null,
            ],
        ]);
    }

    /**
     * Appointments linked to this job order (job_order_id, set manually by
     * staff/owner or automatically on ready_for_fitting — CUSTOMER-WORKFLOW.md
     * §7.4), reduced to the same customer-safe field subset
     * AppointmentController::myAppointments() already uses elsewhere — no
     * staff assignment, no internal notes, no payment reference/receipt.
     * Reuses the existing JobOrder::appointments() relationship; no new table.
     */
    private function buildCustomerSafeAppointments(JobOrder $jobOrder): array
    {
        return $jobOrder->appointments()
            ->with(['service:id,name', 'branch:id,name,address,city'])
            ->orderByDesc('scheduled_at')
            ->get()
            ->map(fn ($appointment) => [
                'id' => $appointment->id,
                'appointment_type' => $appointment->appointment_type,
                'status' => $appointment->status,
                'scheduled_at' => $appointment->scheduled_at,
                'checked_in_at' => $appointment->checked_in_at,
                'duration_minutes' => $appointment->duration_minutes,
                'service_name' => $appointment->service?->name,
                'branch' => $appointment->branch ? [
                    'name' => $appointment->branch->name,
                    'address' => $appointment->branch->address,
                    'city' => $appointment->branch->city,
                ] : null,
            ])
            ->values()
            ->all();
    }

    /**
     * Best-effort real "when did this stage happen" per pipeline stage, for
     * the customer detail page's timeline — assembled from data that's
     * already tracked, not a dedicated stage-history table (none exists).
     * design/pattern_making/cutting/sewing/qc_ironing come from the
     * job_order_staff pivot's assigned_at (when staff was put on that
     * stage — the earliest, if more than one staff worked it). Stages with
     * no tracked timestamp anywhere (mass_cutting_printing, ready_for_fitting,
     * completed) are left null rather than guessed — the frontend just
     * omits the date/time line for those instead of showing a wrong one.
     */
    private function buildStageTimestamps(JobOrder $jobOrder): array
    {
        $stageStart = fn (string $stage) => $jobOrder->staffStages
            ->where('pivot.stage', $stage)
            ->pluck('pivot.assigned_at')
            ->filter()
            ->min();

        return [
            'pending' => $jobOrder->created_at,
            'design' => $stageStart('design'),
            'pattern_making' => $stageStart('pattern_making'),
            'mass_cutting_printing' => null,
            'cutting' => $stageStart('cutting'),
            'sewing' => $stageStart('sewing'),
            'ready_for_fitting' => null,
            'final_adjustments' => $jobOrder->first_adjustment_at,
            'qc_ironing' => $stageStart('qc_ironing'),
            'ready_for_pickup' => $jobOrder->ready_for_pickup_at,
            'completed' => null,
        ];
    }

    public function show(string $trackingCode): JsonResponse
    {
        $raw = strtoupper(trim($trackingCode));
        $normalized = str_replace(['-', ' '], '', $raw);

        $jobOrder = JobOrder::where('tracking_code', $raw)
            ->orWhereRaw("REPLACE(REPLACE(tracking_code, '-', ''), ' ', '') = ?", [$normalized])
            ->orWhere('order_number', $raw)
            ->orWhereRaw("REPLACE(REPLACE(order_number, '-', ''), ' ', '') = ?", [$normalized])
            ->with(['store:id,name,slug,logo_path', 'service:id,name', 'catalogItem:id,name', 'staffStages'])
            ->first();

        if (! $jobOrder) {
            return response()->json([
                'success' => false,
                'message' => 'No order found for that tracking code or order number. Double-check the code and try again.',
            ], 404);
        }

        return response()->json([
            'success' => true,
            'data' => [
                'order_number' => $jobOrder->order_number,
                'tracking_code' => $jobOrder->tracking_code,
                'status' => $jobOrder->status,
                'garment_category' => $jobOrder->garment_category,
                'catalog_item_name' => $jobOrder->catalogItem?->name,
                'service_name' => $jobOrder->service?->name,
                'is_rush' => (bool) $jobOrder->is_rush,
                'due_date' => $jobOrder->due_date,
                'estimated_ready_at' => $jobOrder->estimated_ready_at,
                'total_amount' => (float) $jobOrder->total_amount,
                'balance' => (float) $jobOrder->balance,
                'payment_status' => $jobOrder->payment_status,
                'created_at' => $jobOrder->created_at,
                'updated_at' => $jobOrder->updated_at,
                'repair_note' => $jobOrder->custom_order_data['repair_note'] ?? null,
                'customer_material_status' => $jobOrder->customer_material_status,
                'progress_photos' => $jobOrder->progress_photos,
                'stage_timestamps' => $this->buildStageTimestamps($jobOrder),
                'appointments' => $this->buildCustomerSafeAppointments($jobOrder),
                'store' => $jobOrder->store ? [
                    'name' => $jobOrder->store->name,
                    'slug' => $jobOrder->store->slug,
                    'logo_path' => $jobOrder->store->logo_path,
                ] : null,
            ],
        ]);
    }
}
